### ISSUE TITLE
Migrate away from Bower

### ISSUE THREAD

**Issue by DerekTBrown** [CMU-313/hospitalrun-frontend#2]
Bower is now deprecated.  Need to update static dependencies to Yarn.

**Comment by DerekTBrown** [comment]
Discussed previously: https://github.com/HospitalRun/hospitalrun-frontend

**Comment by DerekTBrown** [comment]
Currently working on this.  Stuck on an error:

```
[5/5] Building fresh packages...
error /usr/src/app/node_modules/leveldown: Command failed.
Exit code: 2
Command: prebuild --install
Arguments: 
Directory: /usr/src/app/node_modules/leveldown
Output:
prebuild info begin Prebuild version 4.5.0
prebuild ERR! configure error 
prebuild ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
prebuild ERR! stack     at Object.failNoPython (/usr/src/app/node_modules/node-gyp/lib/configure.js:483:19)
prebuild ERR! stack     at Object.<anonymous> (/usr/src/app/node_modules/node-gyp/lib/configure.js:397:16)
prebuild ERR! stack     at F (/usr/src/app/node_modules/which/which.js:68:16)
prebuild ERR! stack     at E (/usr/src/app/node_modules/which/which.js:80:29)
prebuild ERR! stack     at /usr/src/app/node_modules/which/which.js:89:16
prebuild ERR! stack     at /usr/src/app/node_modules/isexe/index.js:42:5
prebuild ERR! stack     at /usr/src/app/node_modules/isexe/mode.js:8:5
prebuild ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
prebuild ERR! not ok 
prebuild ERR! build Error: Can't find Python executable "python", you can set the PYTHON env variable.
prebuild ERR! build     at Object.failNoPython (/usr/src/app/node_modules/node-gyp/lib/configure.js:483:19)
prebuild ERR! build     at Object.<anonymous> (/usr/src/app/node_modules/node-gyp/lib/configure.js:397:16)
prebuild ERR! build     at F (/usr/src/app/node_modules/which/which.js:68:16)
prebuild ERR! build     at E (/usr/src/app/node_modules/which/which.js:80:29)
prebuild ERR! build     at /usr/src/app/node_modules/which/which.js:89:16
prebuild ERR! build     at /usr/src/app/node_modules/isexe/index.js:42:5
prebuild ERR! build     at /usr/src/app/node_modules/isexe/mode.js:8:5
prebuild ERR! build     at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by DerekTBrown** [comment]
Fixed by adding `python` and `build-base` to the list of dependencies.  This is because `node-gyp` requires python.

**Comment by DerekTBrown** [comment]
https://github.com/HospitalRun/hospitalrun-frontend/pull/1301
